Aircraft:
  Eagle:
    hitpoints: 100
    speed: 200
    fireInterval: 1
  Raptor:
    hitpoints: 20
    speed: 80
    directions: [[45, 80], [-45, 160], [45, 80]]
    fireInterval: 0
  Avenger:
    hitpoints: 40
    speed: 50
    directions: [[45, 50], [0, 50], [-45, 100], [0, 50], [45, 50]]
    fireInterval: 2
Projectile:
  AlliedBullet:
    damage: 10
    speed: 300
  EnemyBullet:
    damage: 10
    speed: 300
  Missile:
    damage: 200
    speed: 150
Pickup:
  HealthRefill:
    repair: 25
  MissileRefill:
    collectMissiles: 3
  FireSpread:
  FireRate:
